version: '3.8'

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    image: lg-pwd_client-nuxt_bridge
    container_name: lg-pwd_client-nuxt_bridge
    command: yarn run dev
    restart: always
    tty: true
    volumes:
      - ./client:/src:delegated
      - /src/node_modules
    ports:
      - 3000:3000
    networks:
      - container-link-nuxt_bridge

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: lg-pwd_backend-nuxt_bridge
    container_name: lg-pwd_backend-nuxt_bridge
    environment:
      DJANGO_SETTINGS_MODULE: config.settings_local
    command: ./manage.py runserver 0.0.0.0:8000
    restart: always
    tty: true
    volumes:
      - ./backend:/src
    ports:
      - 8000:8000
    networks:
      - container-link-nuxt_bridge

  postgres:
    image: postgres:12-bullseye
    container_name: lg-pwd_postgres-nuxt_bridge
    environment:
      POSTGRES_USER: lgpwd
      POSTGRES_DB: lgpwd
      POSTGRES_PASSWORD: lgpwd
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./local-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - container-link-nuxt_bridge

networks:
  default:
    external: true
    name: nuxt-bridge
  container-link-nuxt_bridge:
    name: lg-pwd_network-nuxt_bridge
