# Generated by Django 4.0.3 on 2022-09-29 17:33

from django.db import migrations

from psqlextra.backend.migrations.operations import PostgresAddListPartition


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220929_1733'),
    ]

    operations = [
        PostgresAddListPartition(
           model_name="PartitionedUserProfile",
           name="region_1",
           values=[1],
        ),
        PostgresAddListPartition(
           model_name="PartitionedUserProfile",
           name="region_34",
           values=[34],
        ),
       PostgresAddListPartition(
           model_name="PartitionedUserCityCa",
           name="region_1",
           values=[1],
        ),
        PostgresAddListPartition(
           model_name="PartitionedUserCityCa",
           name="region_34",
           values=[34],
        ),
        PostgresAddListPartition(
           model_name="PartitionedResetPassword",
           name="region_1",
           values=[1],
        ),
        PostgresAddListPartition(
           model_name="PartitionedResetPassword",
           name="region_34",
           values=[34],
        ),
    ]

