# Generated by Django 4.0.3 on 2022-10-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220929_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fax_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_subscribe',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
