# Generated by Django 4.0.3 on 2022-10-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_fax_number_remove_user_is_subscribe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitioneduserprofile',
            name='birthday_day',
        ),
        migrations.RemoveField(
            model_name='partitioneduserprofile',
            name='birthday_month',
        ),
        migrations.RemoveField(
            model_name='partitioneduserprofile',
            name='birthday_year',
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='age',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='birthday',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='disability_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='障がいカテゴリー'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='disablity_grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='障がい等級'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='disablity_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='手帳の号数'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='disablity_prefecture',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手帳の都道府県'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=32, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='get_disaster_notification',
            field=models.BooleanField(default=True, verbose_name='災害時のお知らせ通知-有効'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='get_notification',
            field=models.BooleanField(default=True, verbose_name='通常のお知らせ通知-有効'),
        ),
        migrations.AlterField(
            model_name='partitioneduserprofile',
            name='disability_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='障がい種別（3手帳）'),
        ),
        migrations.AlterField(
            model_name='partitioneduserprofile',
            name='user_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
