# Generated by Django 4.0.3 on 2022-11-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_notification_is_disaster_info_and_more'),
        ('account', '0006_remove_partitioneduserprofile_birthday_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facility', verbose_name='施設'),
        ),
    ]
