# Generated by Django 4.0.3 on 2022-12-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_partitioneduserprofile_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='is_dangerous',
            field=models.BooleanField(default=False, verbose_name='要注意人物-有効'),
        ),
    ]
