# Generated by Django 4.0.3 on 2023-01-19 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_partitioneduserprofile_disability_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='disability_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, default=list, null=True, size=None, verbose_name='障がい種別（3手帳）'),
        ),
    ]
