# Generated by Django 4.0.3 on 2023-06-23 19:24

from django.db import migrations

from psqlextra.backend.migrations.operations import PostgresAddListPartition


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20230511_1319'),
    ]

    operations = [
        PostgresAddListPartition(
           model_name="PartitionedUserProfile",
           name="region_67",
           values=[67],
       ),
       PostgresAddListPartition(
           model_name="PartitionedUserCityCa",
           name="region_67",
           values=[67],
        ),
        PostgresAddListPartition(
           model_name="PartitionedResetPassword",
           name="region_67",
           values=[67],
        ),
        PostgresAddListPartition(
           model_name="FacilityManger",
           name="region_67",
           values=[67],
        ),   
    ]
