# Generated by Django 4.0.3 on 2023-06-23 20:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_partitioneduserprofile_list_disability_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitioneduserprofile',
            name='disability_category',
        ),
        migrations.RenameField(
            model_name='partitioneduserprofile',
            old_name='list_disability_category',
            new_name='disability_category',
        ),
    ]
