# Generated by Django 4.2.5 on 2023-10-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20231017_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='age_range',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='年齢範囲'),
        ),
    ]
