# Generated by Django 4.2.5 on 2024-01-22 12:58

from django.db import migrations

from psqlextra.backend.migrations.operations import PostgresAddListPartition

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_partitioneduserprofile_age_range'),
    ]

    operations = [
        PostgresAddListPartition(
           model_name="PartitionedUserProfile",
           name="region_69",
           values=[69],
       ),
       PostgresAddListPartition(
           model_name="PartitionedUserCityCa",
           name="region_69",
           values=[69],
        ),
        PostgresAddListPartition(
           model_name="PartitionedResetPassword",
           name="region_69",
           values=[69],
        ),
        PostgresAddListPartition(
           model_name="FacilityManger",
           name="region_69",
           values=[69],
        ),   
    ]
