# Generated by Django 4.2.5 on 2024-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20240122_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='expire_date1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='有効期限1'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='expire_date2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='有効期限2'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='expire_date3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='有効期限3'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='expire_date4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='有効期限4'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='expire_date5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='有効期限5'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='expire_date6',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='有効期限6'),
        ),
        migrations.AddField(
            model_name='partitioneduserprofile',
            name='expire_date7',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='有効期限7'),
        ),
    ]
