export const layoutInfo = [
  {
    city_name: 'minato_city',
    city_code: '131032',
    layout: 'default',
    nav: 'NavigationButton',
  },
  {
    city_name: 'chigasaki',
    city_code: '142077', 
    layout: 'Chigasaki',
    nav: 'NavigationLink',
  },
  {
    city_name: 'edogawa',
    city_code: '131237', 
    layout: 'Edogawa',
    nav: 'NavigationLink',
  },
]








// / export const mainFunctionData = [

//   {
//     city_name: 'minato_city',
//     city_code: '131032',
//     notification: false,
//     notification_title: 'お知らせ一覧',
//     notification_url: '/notification?citycode=',
//     login: false,
//     login_title: 'ログイン•会員登録',
//     login_url: '/account?citycode=',
//     mirairo: false,
//     mirairo_title: 'ミライロID',
//     mirairo_url: '/mirairo?citycode=',
//     facility: false,
//     facility_title: '障害者施設 一覧',
//     facility_url: '/facility?citycode=',
//     congestion: false,
//     congestion_title: '',
//     congestion_url: '',
//     reservation: false,
//     reservation_title: '短期入所 予約',
//     reservation_url: '/reservation?citycode=',
//     reservation_history: false,
//     reservation_history_title: '短期入所 予約履歴',
//     reservation_history_url: '/history?citycode=',
//     faq: false,
//     faq_title: 'よくある質問',
//     faq_url: '/faq?citycode=',
//     term_of_service: false,
//     term_of_service_title: '利用規約',
//     term_of_service_url: '/termofservice?citycode=',
//     notification_management: false,
//     notification_management_title: 'お知らせ管理',
//     notification_management_url: '/admin/notification?citycode=',
//     user_managemant: false,
//     user_managemant_title: 'ユーザー管理',
//     user_managemant_url: '/admin/account/list?citycode=',
//     inquiry_management: false,
//     inquiry_management_title: 'お問い合わせ管理',
//     inquiry_management_url: '/admin/faq/list?citycode=',
//     survey: false,
//     survey_title: '',
//     survey_url: '',
//   },

//   {
//     city_name: 'chigasaki',
//     city_code: '142077',
//     notification: false,
//     notification_title: 'お知らせ一覧',
//     notification_url: '/notification?citycode=',
//     login: false,
//     login_title: 'ログイン•会員登録',
//     login_url: '/account?citycode=',
//     mirairo: false,
//     mirairo_title: 'ミライロID',
//     mirairo_url: '/mirairo?citycode=',
//     facility: false,
//     facility_title: '障害者施設 一覧',
//     facility_url: '/facility?citycode=',
//     congestion: false,
//     congestion_title: '',
//     congestion_url: '',
//     reservation: false,
//     reservation_title: '短期入所 予約',
//     reservation_url: '/reservation?citycode=',
//     reservation_history: false,
//     reservation_history_title: '短期入所 予約履歴',
//     reservation_history_url: '/history?citycode=',
//     faq: false,
//     faq_title: 'よくある質問',
//     faq_url: '/faq?citycode=',
//     term_of_service: false,
//     term_of_service_title: '利用規約',
//     term_of_service_url: '/termofservice?citycode=',
//     notification_management: false,
//     notification_management_title: 'お知らせ管理',
//     notification_management_url: '/admin/notification?citycode=',
//     user_managemant: false,
//     user_managemant_title: 'ユーザー管理',
//     user_managemant_url: '/admin/account/list?citycode=',
//     inquiry_management: false,
//     inquiry_management_title: 'お問い合わせ管理',
//     inquiry_management_url: '/admin/faq/list?citycode=',
//     survey: false,
//     survey_title: '',
//     survey_url: '',
//   },

// ]