export const notificationField = [

    {
        city_name: 'minato_city',
        city_code: '131032',
        segment_fileds: false,
        is_segment_birthday_month: false,
        is_disaster_info: false,
        
    },
    {
        city_name: 'chigasaki',
        city_code: '142077', 
        segment_fileds: true,
        is_segment_birthday: true,
        is_segment_birthday_month: false,
        is_disaster_info: true,
        addrressOptions: [
            "赤羽根",
            "赤松町",
            "旭が丘",
            "甘沼",
            "今宿",
            "円蔵",
            "香川",
            "小桜町",
            "小和田",
            "幸町",
            "汐見台",
            "下寺尾",
            "下町屋",
            "松林",
            "白浜町",
            "新栄町",
            "十間坂",
            "芹沢",
            "高田",
            "代官町",
            "茅ヶ崎",
            "堤",
            "鶴が台",
            "出口町",
            "常盤町",
            "共恵",
            "中海岸",
            "中島",
            "行谷",
            "南湖",
            "西久保",
            "萩園",
            "浜須賀",
            "浜竹",
            "浜之郷",
            "浜見平",
            "東海岸北",
            "東海岸南",
            "菱沼",
            "菱沼海岸",
            "ひばりが丘",
            "富士見町",
            "平太夫新田",
            "平和町",
            "本宿町",
            "本村",
            "松尾",
            "松風台",
            "松が丘",
            "松浪",
            "美住町",
            "みずき",
            "緑が浜",
            "室田",
            "元町",
            "柳島海岸",
            "柳島",
            "矢畑",
            "若松町",
        ],
        userTypeChoices: [
            '本人', 
            '家族', 
            '介助者',
            'その他',
        ],
        disabilityTypeChoices: [
            '身体障害者手帳１級',
            '身体障害者手帳２級',
            '身体障害者手帳３級',
            '身体障害者手帳４級',
            '身体障害者手帳５級',
            '身体障害者手帳６級',
            '療育手帳Ａ１',
            '療育手帳Ａ２',
            '療育手帳Ｂ１',
            '療育手帳Ｂ２',
            '精神障害者保健福祉手帳１級',
            '精神障害者保健福祉手帳２級',
            '精神障害者保健福祉手帳３級',
            '自立支援医療（精神通院）',
        ],
    },
    {
        city_name: 'edogawa',
        city_code: '131237', 
        segment_fileds: true,
        is_segment_birthday: true,
        is_segment_birthday_month: true,
        is_disaster_info: false,
        disabilityTypeChoices: [
            '身体障害',
            '知的障害',
            '精神障害',
            '難病',
            '医療的ケア児',
        ],
        notificationTags: [
            'ストマ装具（日常生活用具おむつを含む）',
            '福祉タクシー券',
            '都営交通無料乗車券',
            '有料道路割引'
        ],
        notificationCategories: [
            {text: "イベント", value: 1},
            {text: "学び", value: 2},
            {text: "手続き案内", value: 3},
        ],
    },
    {
        city_name: 'hida',
        city_code: '212172', 
        segment_fileds: true,
        is_segment_birthday: false,
        is_segment_birthday_month: false,
        is_disaster_info: false,
        addrressOptions: [
            "河合",
            "宮川",
            "古川",
            "神岡"
        ],
        ageOptions: [
            {text: "未就学児", value: "0-5"},
            {text: "小中学生", value: "6-15"},
            {text: "16 - 18歳", value: "16-18"},
            {text: "19 - 29歳", value: "19-29"},
            {text: "30 - 39歳", value: "30-39"},
            {text: "40 - 49歳", value: "40-49"},
            {text: "50 - 59歳", value: "50-59"},
            {text: "60 - 69歳", value: "60-69"},
            {text: "70歳以上", value: "70-200"}
        ],
        disabilityTypeChoices: [
            '身体障害者手帳１級',
            '身体障害者手帳２級',
            '身体障害者手帳３級',
            '身体障害者手帳４級',
            '身体障害者手帳５級',
            '身体障害者手帳６級',
            '療育手帳Ａ１',
            '療育手帳Ａ２',
            '療育手帳Ｂ１',
            '療育手帳Ｂ２',
            '精神障害者保健福祉手帳１級',
            '精神障害者保健福祉手帳２級',
            '精神障害者保健福祉手帳３級',
            '自立支援医療（精神通院）',
        ],
        userTypeChoices: [
            '本人', 
            '家族', 
            '介助者',
            'その他',
        ],
        notificationCategories: [
            {text: "イベント案内", value: 1},
            {text: "手続き案内", value: 2},
            {text: "行事の様子", value: 3},
        ],
    },
    {
        city_name: 'nasushiobara',
        city_code: '092134', 
        segment_fileds: true,
        is_segment_birthday: false,
        is_segment_birthday_year: true,
        is_segment_birthday_month: true,
        is_disaster_info: false,
        notificationTags: [
            '精神障害者保健福祉手帳',
            '自立支援医療（精神通院）',
            '日常生活用具（ストマ・おむつ）',
            '子育て（発達支援・療育）'
        ],
        userTypeChoices: [
            '本人', 
            '家族（介助者）', 
            '事業所',
            'その他',
        ],
    },
]