export const pageTitle = [
    {
        city_name: 'minato_city',
        city_code: '131032',
        history_title: '短期入所 予約履歴',
        reservation_title: '短期入所 予約',
        notification_title: 'お知らせ一覧',
        information_title: 'サービス一覧',
        mirairo_title: 'ミライロID連携',
        faq_title: 'お問い合わせ・よくある質問',
    },
    {
        city_name: 'chigasaki',
        city_code: '142077',
        reservation_title: 'オンライン相談予約',
        notification_title: 'お知らせ',
        booklet_title: '福祉の案内',
        congestion_title: '混雑状況',
        information_title: '手話通訳者・要約筆記者の派遣',
        mirairo_title: 'ミライロID連携',
        faq_title: 'お問い合わせ・よくある質問',
    },
    {
        city_name: 'edogawa',
        city_code: '131237',
        notification_title: 'お知らせ',
        booklet_title: '障害福祉のしおり',
        congestion_title: '事業者一覧',
        mirairo_title: 'ミライロID連携',
        faq_title: 'お問い合わせ・よくある質問',
    },
    {
        city_name: 'hida',
        city_code: '212172',
        notification_title: 'お知らせ',
        booklet_title: '障がい者支援情報',
        information_title: '各種相談窓口',
        mirairo_title: 'ミライロID連携',
        faq_title: 'お問い合わせ・よくある質問',
    },
    {
        city_name: 'nasushiobara',
        city_code: '092134',
        notification_title: 'お知らせ',
        booklet_title: '障がい者支援情報',
        information_title: '各種相談窓口',
        mirairo_title: 'ミライロID連携',
        faq_title: 'お問い合わせ・よくある質問',
    },
]