variable "name" {}
variable "region" {}
variable "vpc_cidr" {}
//variable "public_subnet_a_cidr" {}
//variable "public_subnet_c_cidr" {}
//variable "private_subnet_a_cidr" {}
//variable "private_subnet_c_cidr" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "db_port" {}
variable "bastion_ami" {}
variable "bastion_key_pair" {}
variable "retention_in_days" {}
variable "allow_ips" {}
