# Generated by Django 3.2.6 on 2021-08-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=256)),
                ('city_code', models.CharField(max_length=6, unique=True)),
                ('active_since', models.DateField(blank=True, null=True, verbose_name='利用開始日')),
                ('active_until', models.DateField(blank=True, null=True, verbose_name='利用終了日')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='代表メールアドレス')),
                ('header_image', models.CharField(max_length=256, verbose_name='自治体別固定ヘッダー画像')),
                ('header_text', models.CharField(default='障害者アプリ', max_length=128)),
                ('base_color', models.CharField(default='purple', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '自治体',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=2048)),
                ('active_since', models.DateTimeField(verbose_name='掲載開始日時')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name_plural': 'お知らせ',
            },
        ),
        migrations.CreateModel(
            name='MirairoConnectRegionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('auth_url', models.CharField(max_length=255, verbose_name='ミライロ側の認証画面URL')),
                ('client_id', models.CharField(max_length=255, verbose_name='OAuth2クライアントID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='OAuth2クライアントシークレット')),
                ('redirect_url_origin', models.CharField(max_length=255, verbose_name='リダイレクトURLのオリジン')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mirairo_connect_profile', to='app.region')),
            ],
            options={
                'verbose_name': 'ミライロ連携自治体設定',
                'verbose_name_plural': 'ミライロ連携自治体設定',
            },
        ),
        migrations.CreateModel(
            name='FirebaseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name_plural': 'Firebaseトークン',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('address', models.CharField(max_length=1024, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name_plural': '施設',
            },
        ),
    ]
