# Generated by Django 3.2.6 on 2021-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirairoUserCertificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('certificate_type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('barrier_grade', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('barrier_variety', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('issued_by', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('myna_confirmed', models.BooleanField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('date_of_reissue', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ユーザのミライロ情報',
                'verbose_name_plural': 'ユーザのミライロ情報',
            },
        ),
        migrations.CreateModel(
            name='MirairoUserConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=255)),
                ('token_type', models.CharField(max_length=255)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'ユーザのミライロ連携トークン',
                'verbose_name_plural': 'ユーザのミライロ連携トークン',
            },
        ),
        migrations.AddField(
            model_name='mirairoconnectregionprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='ミライロID連携を有効にする'),
        ),
    ]
