# Generated by Django 3.2.6 on 2021-09-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210910_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirairouserconnection',
            name='access_token',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='mirairouserconnection',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
    ]
