# Generated by Django 3.2.6 on 2021-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210910_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirairouserconnection',
            name='expires_in',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
