# Generated by Django 3.2.6 on 2021-09-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210910_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mirairousercertificate',
            options={'verbose_name': 'ユーザの障害者手帳情報', 'verbose_name_plural': 'ユーザの障害者手帳情報'},
        ),
        migrations.AddField(
            model_name='region',
            name='top_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自治体別トップ画像'),
        ),
    ]
