# Generated by Django 3.2.6 on 2021-09-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210911_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='contact',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('consultation_service', '相談窓口'), ('disabled_facility', '障害者施設')], default='disabled_facility', max_length=32),
        ),
        migrations.AddField(
            model_name='facility',
            name='fax_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='google_map',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='target',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
