# Generated by Django 3.2.7 on 2021-10-22 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20210913_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='表示名')),
                ('message_type', models.CharField(choices=[('inquiry', 'お問合せ'), ('reply', '返信')], default='inquiry', max_length=32)),
                ('category', models.CharField(choices=[('disability', '障害者施設'), ('service', '相談窓口'), ('mirairo', 'ミライロ'), ('reservation', '予約'), ('login', 'ログイン'), ('other', 'その他')], default='other', max_length=32)),
                ('contents', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '未対応'), ('inspecting', '対応中'), ('completed', '対応済み')], db_index=True, default='pending', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_by', to=settings.AUTH_USER_MODEL)),
                ('created_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_to', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name_plural': 'お問合せ',
            },
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['created_at'], name='app_inquiry_created_60b111_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['created_at', 'status'], name='app_inquiry_created_2e3cfe_idx'),
        ),
    ]
