# Generated by Django 3.2.8 on 2021-11-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211022_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('contents', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': '施設カテゴリ',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('app', '本アプリの活用方法'), ('notification', 'お知らせ内容'), ('registration', '会員登録'), ('mirairo', 'ミライロID'), ('reservation', '短期入所施設予約'), ('other', 'ご意見、その他')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='facility',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facilitycategory'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['region', 'facility_type', 'category'], name='app_facilit_region__2642d5_idx'),
        ),
    ]
