# Generated by Django 4.0.3 on 2022-09-26 12:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_uploadedfile_notificationfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_ca_endpoint', models.CharField(blank=True, max_length=256, null=True, verbose_name='CityCaアクセスURL')),
                ('city_ca_apikey', models.CharField(blank=True, max_length=255, null=True, verbose_name='CityCaアクセスAPIKey')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('messages', models.JSONField(blank=True, default=[], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name_plural': '予約システム連携情報',
            },
        ),
    ]
