# Generated by Django 4.0.3 on 2022-09-29 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_reservationconnection'),
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='PartitionedFirebaseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name_plural': 'Firebaseトークン - パーティション',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['LIST'],
                'key': ['region_id'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='PartitionedFirebaseToken',
            name='default',
        ),
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='PartitionedInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='表示名')),
                ('message_type', models.CharField(choices=[('inquiry', 'お問合せ'), ('reply', '返信')], default='inquiry', max_length=32)),
                ('category', models.CharField(choices=[('app', '本アプリの活用方法'), ('notification', 'お知らせ内容'), ('registration', '会員登録'), ('mirairo', 'ミライロID'), ('reservation', '短期入所施設予約'), ('other', 'ご意見、その他')], default='other', max_length=32)),
                ('contents', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '未対応'), ('inspecting', '対応中'), ('completed', '対応済み')], db_index=True, default='pending', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_by', to=settings.AUTH_USER_MODEL)),
                ('created_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_to', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name_plural': 'お問合せ - パーティション',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['LIST'],
                'key': ['region_id'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='PartitionedInquiry',
            name='default',
        ),
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='PartitionedMirairoUserCertificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('certificate_type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('barrier_grade', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('barrier_variety', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('issued_by', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('myna_confirmed', models.BooleanField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('date_of_reissue', models.DateField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name': 'ユーザの障害者手帳情報 - パーティション',
                'verbose_name_plural': 'ユーザの障害者手帳情報 - パーティション',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['LIST'],
                'key': ['region_id'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='PartitionedMirairoUserCertificate',
            name='default',
        ),
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='PartitionedMirairoUserConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=65535)),
                ('token_type', models.CharField(max_length=255)),
                ('expires_in', models.BigIntegerField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=65535, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name': 'ユーザのミライロ連携トークン - パーティション',
                'verbose_name_plural': 'ユーザのミライロ連携トークン - パーティション',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['LIST'],
                'key': ['region_id'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='PartitionedMirairoUserConnection',
            name='default',
        ),
        migrations.AddField(
            model_name='mirairousercertificate',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region'),
        ),
        migrations.AddField(
            model_name='mirairouserconnection',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region'),
        ),
        migrations.AddField(
            model_name='notificationfile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region'),
        ),
        migrations.AddIndex(
            model_name='partitionedinquiry',
            index=models.Index(fields=['created_at'], name='app_partiti_created_422a01_idx'),
        ),
        migrations.AddIndex(
            model_name='partitionedinquiry',
            index=models.Index(fields=['created_at', 'status'], name='app_partiti_created_1eaf62_idx'),
        ),
    ]
