# Generated by Django 4.0.3 on 2022-09-29 17:34

from django.db import migrations

from psqlextra.backend.migrations.operations import PostgresAddListPartition


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220929_1733'),
    ]

    operations = [
        PostgresAddListPartition(
           model_name="PartitionedInquiry",
           name="region_1",
           values=[1],
        ),
        PostgresAddListPartition(
           model_name="PartitionedInquiry",
           name="region_34",
           values=[34],
        ),
        PostgresAddListPartition(
           model_name="PartitionedMirairoUserConnection",
           name="region_1",
           values=[1],
        ),
        PostgresAddListPartition(
           model_name="PartitionedMirairoUserConnection",
           name="region_34",
           values=[34],
        ),
        PostgresAddListPartition(
           model_name="PartitionedMirairoUserCertificate",
           name="region_1",
           values=[1],
        ),
        PostgresAddListPartition(
           model_name="PartitionedMirairoUserCertificate",
           name="region_34",
           values=[34],
        ),
        PostgresAddListPartition(
           model_name="PartitionedFirebaseToken",
           name="region_1",
           values=[1],
        ),
        PostgresAddListPartition(
           model_name="PartitionedFirebaseToken",
           name="region_34",
           values=[34],
        ),
    ]
