# Generated by Django 4.0.3 on 2022-10-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220929_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='担当部署'),
        ),
        migrations.AddField(
            model_name='region',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='電話番号'),
        ),
    ]
