# Generated by Django 4.0.3 on 2022-12-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_notification_is_disaster_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='advertising_image1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='自治体別広告画像1'),
        ),
        migrations.AddField(
            model_name='region',
            name='advertising_image2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='自治体別広告画像2'),
        ),
        migrations.AddField(
            model_name='region',
            name='advertising_image3',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='自治体別広告画像3'),
        ),
        migrations.AddField(
            model_name='region',
            name='advertising_image4',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='自治体別広告画像4'),
        ),
        migrations.AddField(
            model_name='region',
            name='dark_color',
            field=models.CharField(default='purple', max_length=128),
        ),
        migrations.AddField(
            model_name='region',
            name='footer_pc_image',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='自治体別固定フッターPC画像'),
        ),
        migrations.AddField(
            model_name='region',
            name='footer_sp_image',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='自治体別固定フッターSP画像'),
        ),
        migrations.AddField(
            model_name='region',
            name='light_color',
            field=models.CharField(default='purple', max_length=128),
        ),
    ]
