# Generated by Django 4.0.3 on 2022-12-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_region_advertising_image1_region_advertising_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='term_of_service',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
