# Generated by Django 4.0.3 on 2022-12-14 14:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_partitionedfirebasetoken_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cloud Messaging API Key')),
                ('sns_arn', models.CharField(blank=True, max_length=500, null=True, verbose_name='プッシュ通知プラットフォーム ARN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name_plural': 'FCM連携情報',
            },
        ),
    ]
