# Generated by Django 4.0.3 on 2022-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_notification_segment_address_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='segment_address_block',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
