# Generated by Django 4.0.3 on 2023-01-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_faqcategory_faq_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_body', models.TextField(blank=True, max_length=1500, null=True, verbose_name='お知らせ')),
                ('inquiry_body', models.TextField(blank=True, max_length=1500, null=True, verbose_name='お問い合わせ')),
                ('signup_body', models.TextField(blank=True, max_length=1500, null=True, verbose_name='会員登録')),
                ('reset_password_body', models.TextField(blank=True, max_length=1500, null=True, verbose_name='パスワードリセット')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='app.region')),
            ],
            options={
                'verbose_name_plural': '自治体別メールテキスト',
            },
        ),
    ]
