# Generated by Django 4.0.3 on 2023-06-23 19:32

from django.db import migrations

from psqlextra.backend.migrations.operations import PostgresAddListPartition


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_region_favicon_image'),
    ]

    operations = [
        PostgresAddListPartition(
           model_name="PartitionedInquiry",
           name="region_67",
           values=[67],
        ),
        PostgresAddListPartition(
           model_name="PartitionedMirairoUserConnection",
           name="region_67",
           values=[67],
        ),
        PostgresAddListPartition(
           model_name="PartitionedMirairoUserCertificate",
           name="region_67",
           values=[67],
        ),
        PostgresAddListPartition(
           model_name="PartitionedFirebaseToken",
           name="region_67",
           values=[67],
        ),
    ]
