# Generated by Django 4.0.3 on 2023-06-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_reservationconnection_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='segment_notification_category',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='セグメント配信-お知らせ配信のカテゴリ'),
        ),
        migrations.AddField(
            model_name='notification',
            name='segment_notification_tag',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='セグメント配信-お知らせ配信のタグ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_disaster_info',
            field=models.BooleanField(default=False, verbose_name='災害情報を有効にする'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='segment_address_block',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='セグメント配信-住所'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='segment_birthday',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='セグメント配信-生年月日'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='segment_disability_type',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='セグメント配信-障がい種別'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='segment_user_type',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='セグメント配信-障がい児者との関係'),
        ),
    ]
