# Generated by Django 4.0.3 on 2023-08-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_notification_segment_notification_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusFocusConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_focus_endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='PlusFocusアクセスURL')),
                ('plus_focus_apikey', models.CharField(blank=True, max_length=255, null=True, verbose_name='PlusFocusアクセスAPIKey')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name': 'PlusFocus連携情報',
                'verbose_name_plural': 'PlusFocus連携情報',
            },
        ),
    ]
