# Generated by Django 4.0.3 on 2023-09-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_plusfocusconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroServiceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklet_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='冊子アクセスURL')),
                ('survey_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='アンケートアクセスAPIKey')),
                ('congestion_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='混雑状況アクセスURL')),
                ('barrier_free_map_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='バリアフリーマップアクセスURL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'verbose_name': 'マイクロサービスURL情報',
                'verbose_name_plural': 'マイクロサービスURL情報',
            },
        ),
    ]
