# Generated by Django 4.2.5 on 2023-10-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_facility_latitude_facility_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='segment_birthday_month',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='セグメント配信-誕生月'),
        ),
    ]
