# Generated by Django 4.2.5 on 2023-10-17 17:11

from django.db import migrations

from psqlextra.backend.migrations.operations import PostgresAddListPartition

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_notification_segment_birthday_month'),
    ]

    operations = [
        PostgresAddListPartition(
           model_name="PartitionedInquiry",
           name="region_68",
           values=[68],
        ),
        PostgresAddListPartition(
           model_name="PartitionedMirairoUserConnection",
           name="region_68",
           values=[68],
        ),
        PostgresAddListPartition(
           model_name="PartitionedMirairoUserCertificate",
           name="region_68",
           values=[68],
        ),
        PostgresAddListPartition(
           model_name="PartitionedFirebaseToken",
           name="region_68",
           values=[68],
        ),
    ]
