# Generated by Django 4.0.3 on 2023-12-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_notification_segment_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylistregionsetting',
            name='list_cash',
            field=models.TextField(blank=True),
        ),
    ]
